FROM lappsgrid/tomcat7:1.2.3

COPY *.war /var/lib/tomcat7/webapps
#COPY tomcat-users-template.xml /var/lib/tomcat7/conf
#COPY startup.sh /usr/bin/startup
#RUN chmod +x /usr/bin/startup
#CMD ["/usr/bin/startup"]
